### ISSUE TITLE
Typo in the quote on the home page

### ISSUE THREAD

**Issue by ddddamian** [freeCodeCampBridgend/website#1]
The following quote has a typo at the start of the second sentence... "The point is to understand. Tehre are only two ways to live your life: as though nothing is a miracle, or as though everything is a miracle."

It should be changed to... 
"The point is to understand. There are only two ways to live your life: as though nothing is a miracle, or as though everything is a miracle."

**Comment by plod** [comment]
good spot you want to do a pr? or should i do it

**Comment by plod** [comment]
fixed by pr #2
